# Generated by Django 3.1.2 on 2021-04-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20210407_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_city',
            field=models.CharField(choices=[('Garhwa', 'Garhwa'), ('Palamu', 'Palamu'), ('Latehar', 'Latehar'), ('Chatra', 'Chatra'), ('Hazaribagh', 'Hazaribagh'), ('Koderma', 'Koderma'), ('Giridih', 'Giridih'), ('Ramgarh', 'Ramgarh'), ('Bokaro', 'Bokaro'), ('Dhanbad', 'Dhanbad'), ('Gumla', 'Gumla'), ('Lohardaga', 'Lohardaga'), ('Simdega', 'Simdega'), ('Ranchi', 'Ranchi'), ('Khunti', 'Khunti'), ('West Singhbhum', 'West Singhbhum'), ('Saraikela Kharsawan', 'Saraikela Kharsawan'), ('East Singhbhum', 'East Singhbhum'), ('Jamtara', 'Jamtara'), ('Deoghar', 'Deoghar'), ('Dumka', 'Dumka'), ('Pakur', 'Pakur'), ('Godda', 'Godda'), ('Sahebganj', 'Sahebganj'), ('Araria', 'Araria'), ('Arwal', 'Arwal'), ('Aurangabad', 'Aurangabad'), ('Banka', 'Banka'), ('Begusarai', 'Begusarai'), ('Bhagalpur', 'Bhagalpur'), ('Bhojpur', 'Bhojpur'), ('Buxar', 'Buxar'), ('Darbhanga', 'Darbhanga'), ('East Champaran', 'East Champaran'), ('Gaya', 'Gaya'), ('Gopalganj', 'Gopalganj'), ('Jamui', 'Jamui'), ('Jehanabad', 'Jehanabad'), ('Khagaria', 'Khagaria'), ('Kishanganj', 'Kishanganj'), ('Kaimur', 'Kaimur'), ('Katihar', 'Katihar'), ('Lakhisarai', 'Lakhisarai'), ('Madhubani', 'Madhubani'), ('Munger', 'Munger'), ('Madhepura', 'Madhepura'), ('Muzaffarpur', 'Muzaffarpur'), ('Nalanda', 'Nalanda'), ('Nawada', 'Nawada'), ('Patna', 'Patna'), ('Purnia', 'Purnia'), ('Rohtas', 'Rohtas'), ('Saharsa', 'Saharsa'), ('Samastipur', 'Samastipur'), ('Sheohar', 'Sheohar'), ('Sheikhpura', 'Sheikhpura'), ('Saran', 'Saran'), ('Sitamarhi', 'Sitamarhi'), ('Supaul', 'Supaul'), ('Siwan', 'Siwan'), ('Vaishali', 'Vaishali'), ('West Champaran', 'West Champaran'), ('Other', 'Other')], default='Patna', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck'), ('tractor', 'Tractor'), ('auto rickshaw', 'Auto Rickshaw'), ('agriculture_instrument', 'Agriculture_instrument')], default='car', max_length=25),
        ),
    ]
