# Generated by Django 3.1.2 on 2021-04-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20210415_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Truck', 'Truck'), ('Tractor', 'Tractor'), ('Auto Rickshaw', 'Auto Rickshaw'), ('Agriculture Instrument', 'Agriculture Instrument')], default='Car', max_length=25),
        ),
    ]
