# Generated by Django 3.1.2 on 2021-04-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad1',
            field=models.ImageField(blank=True, null=True, upload_to='car/car_images/'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad2',
            field=models.ImageField(blank=True, null=True, upload_to='car/car_images/'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='popup_ad',
            field=models.ImageField(blank=True, null=True, upload_to='car/car_images/'),
        ),
    ]
