# Generated by Django 3.1.2 on 2021-04-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_auto_20210416_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='ad1_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='ad2_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='popup_ad_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
