# Generated by Django 3.1.2 on 2021-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_auto_20210416_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_owner_phone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo',
            field=models.ImageField(blank=True, null=True, upload_to='car/car_images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='kilometer_driven',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='make_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
