# Generated by Django 3.1.2 on 2021-07-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_auto_20210417_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('phone_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Client Phone Number',
            },
        ),
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name_plural': 'Ads'},
        ),
        migrations.AlterModelOptions(
            name='privacy',
            options={'verbose_name_plural': 'Privacy'},
        ),
    ]
